services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-elevator_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-elevator_pass}
      POSTGRES_DB: ${DB_NAME:-elevator_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-elevator_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elevator-network

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elevator-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-elevator_db}
      - DB_USER=${DB_USER:-elevator_user}
      - DB_PASSWORD=${DB_PASSWORD:-elevator_pass}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_DIRECTORY=/app/logs
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - elevator-network
    command: npm run start

volumes:
  postgres_data:
  redis_data:

networks:
  elevator-network:
    driver: bridge